### ISSUE TITLE
Bug on SAP

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#122]
```
13:28:41] INF Unit exited from zone. zone:5 eid = Unit:def_sap_destruction:4276:5507095668876588631 (1272.5;524.5;312)
[13:28:41] INF Intrusion SAP taken. sap = 5507095668876588631 def_sap_destruction 
[13:28:41] INF Unit died. Killer = Player:3005:213:6104964906917116044 Victim = Unit:def_sap_destruction:4276:5507095668876588631
[13:28:41] INF Entity created. eid:8010066373049598935 def_loot_container_object (979) o:0 p:0 h:100 n: q:1 r:False
[13:28:41] ERR 
Exception Found:
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Perpetuum
Stacktrace:    at Perpetuum.Zones.Intrusion.Outpost.processStabilityChange(StabilityAffectingEvent sap)
   at Perpetuum.Zones.Intrusion.Outpost.HandleTakeOver(SAP sap)
```

**Comment by MikeJeffers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SAP bug](https://trello.com/c/jDc4k74w/27-sap-bug)
