### ISSUE TITLE
IsInLineOfSight breaks at 0 distance

### ISSUE THREAD

**Issue by MikeJeffers** [OpenPerpetuum/PerpetuumServer#140]
Fortunately my debugger caught this before consuming the error (this happens inside some task I presume)
Throws when direction vector properties are NaN, so something generating the direction vector fails.
Produced when killing npc on beta (explosion damage?) 
```
System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=Perpetuum
  StackTrace:
   at Perpetuum.Zones.LineOfSight.IsInLineOfSight(IZone zone, Vector3 origin, Vector3 direction, Single distance, Boolean ballistic) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\LineOfSight.cs:line 113
   at Perpetuum.Zones.LineOfSight.IsInLineOfSight(IZone zone, Unit sourceUnit, Unit targetUnit, Boolean ballistic) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\LineOfSight.cs:line 61
   at Perpetuum.Zones.ZoneExtensions.DoAoeDamage(IZone zone, IBuilder`1 damageBuilder) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Zones\ZoneExtensions.cs:line 176
   at Perpetuum.Units.Unit.<>c__DisplayClass125_0.<DoExplosion>b__0(Task t) in C:\Users\Unavailable\Documents\OpenPerpetuum\PerpetuumServer\src\Perpetuum\Units\Unit.cs:line 482
   at System.Threading.Tasks.Task.Execute()
```

Needs more research as to the originating issue with the bad vector being passed in.

**Comment by MikeJeffers** [comment]
distance = 0
direction (NaN, NaN, NaN)
Resulting `var p` becomes NaN and components are NaN, but when cast to `int` becomes -2^31 which break later computation on ln 114

This function needs to be robust to 0 distance cases!
